# This workflow is triggered on push or pull request events
name: Unity CI

on:
  push:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  # The 'test' job is responsible for running tests on the Unity project
  test:
    name: Test 
    runs-on: ubuntu-latest  # Specifies the runner environment as the latest Ubuntu
    steps:
      # Step to check out the repository code
      - uses: actions/checkout@v4
        with:
          lfs: true  # This will pull LFS files too

      # Step to cache the Library folder to speed up the job
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-

      # Step to debug Docker 
      - name: Debug Docker environment
        run: |
          docker info
          docker version

      # Step to run the Unity tests
      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: 'Crypto Wars' # Specifies project path
          githubToken: ${{ secrets.GITHUB_TOKEN }} # Built-in GitHub Token to authenticate actions
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} # Unity license secret
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }} # Unity Email Secret
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} # Unity Pass Secret

